### ISSUE TITLE
Some recommendations & issues

### ISSUE THREAD

**Issue by jiraiyalegendarysannin** [nccgroup/redsnarf#5]
Hi, first of all, I would like to thank you for this great tool. I have a couple of recommendations/issues;

* On some systems there is no LocalAccountTokenFilterPolicy key in the registry, so psexec or redsnarf can not connect to them. It would be good to notify users so that they could check the registery manually via rdp or powershell etc. (if these are available) .

* datadump function is not opsec safe, most of the AV product can detect password dump related activities, so I think it would be better to disable it by default. Setting the default value of --quick_validate to yes would do the trick.

* I do not understand why many of the functionalities such as -uE, --empire_launcher, -eS, --screenshot etc. implemented in the datadump function, I think they should be implemented somewhere else like -eT --system_tasklist is done.

* -eA --service_accounts function has not been implemented yet.

* -eR, --recorddesktop does not work for windows 10. When I look the schtasks log I can see that "0x800702E4  ERROR_ELEVATION_REQUIRED". Even I manually select Run with highest privileges check box, scheduled task is not executed and it throws the same error. I know that this has nothing to do with redsnarf, I would like to bring this to your attention nonetheless.

Thanks again,

**Comment by dickdavy** [comment]
Hi @jiraiyalegendarysannin 

Thank you for your comments/suggestions. RedSnarf is constantly evolving and hopefully improving with each push so they will certainly be taken on board/fixed and implemented at some level.

Many of the functions which are within the datadump function are there so that they can be run over multiple machines. Other functions tend to be one time only functions. The project may get a rewrite at some stage as it has grown from it's original design.

Please us know if  you have any other suggestions/comments.

Many thanks.
